steal('./helpers/namer_test.js')
	.then('./helpers/tree_test.js')
	.then('./helpers/typer_test.js')
	.then('./helpers/typeNameDescription_test.js')
	.then('./add_test.js').then('./function_test.js')
	.then('./option_test.js').then(
	'./param_test.js',
	'./process_test.js',
	'./property_test.js',
	'./return_test.js',
	'./typedef_test.js')
